# -*- coding: utf-8 -*-
"""easyocr_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194mqUrkNRD5Ny7NN3D-Mpd832nqmoILW
"""

# easyocr_app.py
import streamlit as st
from PIL import Image
import numpy as np
import io
import os

# Only import heavy libs inside functions to avoid startup cost where possible
@st.cache_resource
def load_easyocr_reader(lang_list=["en"]):
    import easyocr
    return easyocr.Reader(lang_list, gpu=False)  # set gpu=True if GPU available

st.set_page_config(page_title="EasyOCR Demo", layout="centered")
st.title("📷 EasyOCR Capstone — Streamlit App")
st.write("Upload images to extract text. Uses EasyOCR under the hood.")

uploaded = st.file_uploader("Upload an image (jpg/png)", type=["jpg","jpeg","png"])
langs = st.multiselect("Languages for OCR (example)", ["en", "hi"], default=["en"])

use_gpu = st.checkbox("Use GPU (if available)", value=False)
if uploaded:
    # Display
    image = Image.open(io.BytesIO(uploaded.read())).convert("RGB")
    st.image(image, caption="Uploaded image", use_container_width=True)
    st.markdown("---")

    # Button to run OCR
    if st.button("Extract text"):
        with st.spinner("Loading OCR reader (this may take a moment)..."):
            reader = load_easyocr_reader(lang_list=langs)
        # Convert to numpy array for easyocr
        img_np = np.array(image)
        results = reader.readtext(img_np)

        if not results:
            st.info("No text detected.")
        else:
            st.subheader("Detected text")
            for (bbox, text, prob) in results:
                st.write(f"- **{text}**  (confidence: {prob:.2f})")
            # Optional: show bounding boxes
            try:
                import cv2
                img_bboxes = img_np.copy()
                for (bbox, text, prob) in results:
                    pts = np.array(bbox).astype(int)
                    cv2.polylines(img_bboxes, [pts], isClosed=True, thickness=2, color=(0,255,0))
                st.image(img_bboxes, caption="With bounding boxes", use_container_width=True)
            except Exception:
                pass

st.write("---")
st.caption("Tip: If deployment fails due to PyTorch / EasyOCR size, see the troubleshooting section.")